# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MemgraphIngester < Formula
  desc "Structure-aware rag for your entire codebase with project memory"
  homepage "https://github.com/ousatov-ua/memgraph-ingester"
  url "https://github.com/ousatov-ua/memgraph-ingester/archive/refs/tags/v12.3.3.tar.gz"
  version "12.3.3"
  sha256 "d1c28a768251cc0137f91e946b35884d28a0740536a45642e4312049eea8ab4f"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ousatov-ua/memgraph-ingester/releases/download/v12.3.3/memgraph-ingester-12.3.3-darwin-arm64.tar.gz"
      sha256 "9e22fb594ba4402fdb0087d5bff0f0ef8d979e859e3c76968208ef2a86f1c6fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ousatov-ua/memgraph-ingester/releases/download/v12.3.3/memgraph-ingester-12.3.3-linux-amd64.tar.gz"
      sha256 "a713978477bfa80d8bbd49765515d5a407a299328f7608c9e0735c9afb7a6691"
    end
  end

  def install
    bin.install "memgraph-ingester"
  end

  test do
    system "#{bin}/memgraph-ingester", "--version"
  end
end
