# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MemgraphIngester < Formula
  desc "Structure-aware rag for your entire codebase with project memory"
  homepage "https://github.com/ousatov-ua/memgraph-ingester"
  url "https://github.com/ousatov-ua/memgraph-ingester/archive/refs/tags/v12.2.1.tar.gz"
  version "12.2.1"
  sha256 "ba4625c04c8176cbd137d2e3b0c09f6c6357e278e983eafc861d9de422337bdf"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ousatov-ua/memgraph-ingester/releases/download/v12.2.1/memgraph-ingester-12.2.1-darwin-arm64.tar.gz"
      sha256 "70dc9cee8f80b783151e17688d9d07c16aeac5e4784a4bf05f0bb43bfba2d434"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ousatov-ua/memgraph-ingester/releases/download/v12.2.1/memgraph-ingester-12.2.1-linux-amd64.tar.gz"
      sha256 "97baffabcc1a7fd67b604c6cc08b2ab3f6bc030e51a557411063b67d2732a043"
    end
  end

  def install
    bin.install "memgraph-ingester"
  end

  test do
    system "#{bin}/memgraph-ingester", "--version"
  end
end
