# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MemgraphIngester < Formula
  desc "Structure-aware rag for your entire codebase with project memory"
  homepage "https://github.com/ousatov-ua/memgraph-ingester"
  url "https://github.com/ousatov-ua/memgraph-ingester/archive/refs/tags/v12.4.3.tar.gz"
  version "12.4.3"
  sha256 "eae2b2a2f71eeb3b9bdecafb069517b60976012040614eaa96e9ed327a6632d7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ousatov-ua/memgraph-ingester/releases/download/v12.4.3/memgraph-ingester-12.4.3-darwin-arm64.tar.gz"
      sha256 "23d54e57d00e391b5036b266f8945226d5f9297ec3f564f9c6bb41e960d1cf4e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ousatov-ua/memgraph-ingester/releases/download/v12.4.3/memgraph-ingester-12.4.3-linux-amd64.tar.gz"
      sha256 "e62453bd98c33368a8134b7ff8b4fefdf6323e1e794215c0c8cde516559860f6"
    end
  end

  def install
    bin.install "memgraph-ingester"
  end

  test do
    system "#{bin}/memgraph-ingester", "--version"
  end
end
